swagger: '2.0'
info:
  title: Toast Cloud SMS
  version: '1.0'
  description: Toast Cloud SMS API Specification
host: "api-sms.cloud.toast.com"
basePath: /sms/v2.2/appKeys/
schemes:
  - https
paths:
  /{appKey}/sender/sms:
    post:
      tags:
      - sms
      summary: 단문 SMS 발송
      operationId: sendSMS
      description: 최대 255자 이내
      consumes:
      - application/json;charset=UTF-8
      parameters:
      - name: appKey
        in: path
        description: Project별 고유의 앱키
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/messageRequestBody"
      responses:
        200:
          description: 너무 길어서 생략
    get:
      tags:
      - sms
      summary: 단문 SMS 발송 리스트 조회 (Parameter는 선택적으로 옮겼음)
      operationId: getSmsSendList
      consumes:
      - application/sjon;charset=UTF-8
      parameters:
        - name: appKey
          in: path
          description: Project별 고유의 앱키
          required: true
          type: string
        - name: requestId
          in: query
          type: string
          maxLength: 25
          description: 요청ID (조건적 필수 - 1)
        - name: startRequestDate
          in: query
          type: string
          format: yyyy-MM-dd HH:mm:ss
          description: 발송 날짜 시작값 (조건적 필수 - 2)
        - name: endRequestDate
          in: query
          type: string
          format: yyyy-MM-dd HH:mm:ss
          description: 발송 날짜 종료값 (조건적 필수 - 2)
        - name: msgStatus
          in: query
          type: string
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
      responses:
        200:
          description: 너무 길어서 생략
  /{appKey}/sender/mms:
    post:
      tags:
      - mms
      summary: 장문 SMS 발송
      operationId: sendMmsWithoutAttachment
      description: 최대 4000자 이내
      consumes:
      - application/json;charset=UTF-8
      parameters:
      - name: appKey
        in: path
        description: Project별 고유의 앱키
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/messageRequestBody"
      responses:
        200:
          description: 너무 길어서 생략
    get:
      tags:
      - mms
      summary: 장문 MMS 발송 리스트 조회 (Parameter는 선택적으로 옮겼음)
      operationId: getMmsSendList
      consumes:
      - application/sjon;charset=UTF-8
      parameters:
        - name: appKey
          in: path
          description: Project별 고유의 앱키
          required: true
          type: string
        - name: requestId
          in: query
          type: string
          maxLength: 25
          description: 요청ID (조건적 필수 - 1)
        - name: startRequestDate
          in: query
          type: string
          format: yyyy-MM-dd HH:mm:ss
          description: 발송 날짜 시작값 (조건적 필수 - 2)
        - name: endRequestDate
          in: query
          type: string
          format: yyyy-MM-dd HH:mm:ss
          description: 발송 날짜 종료값 (조건적 필수 - 2)
        - name: msgStatus
          in: query
          type: string
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
      responses:
        200:
          description: 너무 길어서 생략
definitions:
  recipient:
    type: object
    description: 문자 수신자 정보
    required: [recipientNo]
    properties:
      recipientNo:
        type: string
        maxLength: 50
        description: 수신번호 (countryCode와 조합하여 사용 가능, 최대 1000명)
      countryCode:
        type: string
        maxLength: 255
        description: "국가 번호 [기본값: 82(한국)]"
      internationalRecipientNo:
        type: string
        description: "국가 번호가 포함된 수신 번호 [예)821012345678, recipientNo가 있을 경우 이 값은 무시된다.]"
      templateParameter:
        $ref: "#/definitions/templateParameter"
      recipientGroupingKey:
        type: string
        maxLength: 100
  templateParameter:
    type: object
    required: [key, value]
    description: 템플릿 사용시, 템플릿 내 키 값들 치환을 위한 (수신자별로 적용됨)
    properties:
      key:
        type: string
        description: "치환 키(##key##)"
      value:
        type: string
        description: "치환 키에 매핑되는 Value값"
  messageBody:
    type: object
    description: 문자 발송 요청에 필요한 정보들
    required: [body, sendNo, recipientList]
    properties:
      templateId:
        type: string
        maxLength: 50
        description: 발송 템플릿 ID (단문 50Byte, 장문 4000바이트 제한)
      body:
        type: string
        maxLength: 255
        description: 본문 내용 (개행은 \n으로)
      sendNo:
        type: string
        maxLength: 13
        description: 발신 번호
      requestDate:
        type: string
        format: yyyy-MM-dd HH:mm
        description: 예약 일시
      sendingGroupingKey:
        type: string
        description: 발신자 그룹키
      recipientList:
        type: array
        items:
          $ref: "#/definitions/recipient"
      userId:
        type: string
        maxLength: 100
